language: node_js
node_js: 
  - "lts/*"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
before_script:
  - psql -c 'create database fastfoodfast;' -U postgres
after_success: 
  - npm run cover
